/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfacesApp;

/**
 *
 * @author MADE
 */
public class NuevoInventario extends javax.swing.JPanel {

    /**
     * Creates new form NuevoInventario
     */
    public NuevoInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorRegistroIn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IdProducto = new javax.swing.JLabel();
        CantidadProductos = new javax.swing.JLabel();
        CantidadProductoTXT = new javax.swing.JTextField();
        IdProductoTXT = new javax.swing.JTextField();
        RegresarBoton = new javax.swing.JLabel();
        GuardarProducto = new javax.swing.JLabel();

        ContenedorRegistroIn.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorRegistroIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorRegistroIn.setPreferredSize(new java.awt.Dimension(800, 700));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Incorporación al Inventario");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesApp/IMAGENES2/en-stock (1).png"))); // NOI18N

        IdProducto.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        IdProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdProducto.setText("ID DEL PRODUCTO: ");
        IdProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CantidadProductos.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        CantidadProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadProductos.setText("productos a AGREGAR:");
        CantidadProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CantidadProductoTXT.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N

        IdProductoTXT.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        IdProductoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdProductoTXTActionPerformed(evt);
            }
        });

        RegresarBoton.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        RegresarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegresarBoton.setText("REGRESAR");
        RegresarBoton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegresarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarBotonMouseClicked(evt);
            }
        });

        GuardarProducto.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        GuardarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GuardarProducto.setText("guardar cambios");
        GuardarProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GuardarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarProductoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ContenedorRegistroInLayout = new javax.swing.GroupLayout(ContenedorRegistroIn);
        ContenedorRegistroIn.setLayout(ContenedorRegistroInLayout);
        ContenedorRegistroInLayout.setHorizontalGroup(
            ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorRegistroInLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorRegistroInLayout.createSequentialGroup()
                        .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CantidadProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(IdProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addComponent(IdProductoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorRegistroInLayout.createSequentialGroup()
                        .addComponent(GuardarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CantidadProductoTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorRegistroInLayout.createSequentialGroup()
                                .addComponent(RegresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorRegistroInLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        ContenedorRegistroInLayout.setVerticalGroup(
            ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorRegistroInLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdProductoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadProductoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContenedorRegistroIn, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContenedorRegistroIn, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarBotonMouseClicked
        TablonInventario p = new TablonInventario();
        p.setSize(800, 700);
        ContenedorRegistroIn.removeAll();
        ContenedorRegistroIn.add(p);
        ContenedorRegistroIn.revalidate();
        ContenedorRegistroIn.repaint();
        ContenedorRegistroIn.setSize(800, 700);
        ContenedorRegistroIn.setLocation(200, 0);
    }//GEN-LAST:event_RegresarBotonMouseClicked

    private void GuardarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarProductoMouseClicked

    private void IdProductoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdProductoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdProductoTXTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadProductoTXT;
    private javax.swing.JLabel CantidadProductos;
    private javax.swing.JPanel ContenedorRegistroIn;
    private javax.swing.JLabel GuardarProducto;
    private javax.swing.JLabel IdProducto;
    private javax.swing.JTextField IdProductoTXT;
    private javax.swing.JLabel RegresarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
