/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfacesApp;

/**
 *
 * @author MADE
 */
public class RegistrarProducto extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarProducto
     */
    public RegistrarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorRegistroIn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RegistrarProducto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PrecioTXT = new javax.swing.JTextField();
        CantidadTXT = new javax.swing.JTextField();
        NombeTXT = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContenedorRegistroIn.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorRegistroIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorRegistroIn.setPreferredSize(new java.awt.Dimension(799, 699));
        ContenedorRegistroIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR PRODUCTOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorRegistroIn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 797, 80));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesApp/IMAGENES2/paquete-o-empaquetar_1.png"))); // NOI18N
        ContenedorRegistroIn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 107, 251, 172));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PRECIO DEL PRODUCTO:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorRegistroIn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 199, 60));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID DEL PRODUCTO:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorRegistroIn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 199, 60));

        RegistrarProducto.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        RegistrarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistrarProducto.setText("REGISTRAR");
        RegistrarProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegistrarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarProductoMouseClicked(evt);
            }
        });
        ContenedorRegistroIn.add(RegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 250, 60));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CANTIDAD:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorRegistroIn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 199, 60));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorRegistroIn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 180, 60));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NOMBRE DEL PRODUCTO:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorRegistroIn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 199, 60));
        ContenedorRegistroIn.add(PrecioTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 400, 60));
        ContenedorRegistroIn.add(CantidadTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 400, 60));
        ContenedorRegistroIn.add(NombeTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 400, 60));

        add(ContenedorRegistroIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarProductoMouseClicked
        TablonInventario p = new TablonInventario();
        p.setSize(800, 700);
        ContenedorRegistroIn.removeAll();
        ContenedorRegistroIn.add(p);
        ContenedorRegistroIn.revalidate();
        ContenedorRegistroIn.repaint();
        ContenedorRegistroIn.setSize(800, 700);
        ContenedorRegistroIn.setLocation(200, 0);
    }//GEN-LAST:event_RegistrarProductoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadTXT;
    private javax.swing.JPanel ContenedorRegistroIn;
    private javax.swing.JTextField NombeTXT;
    private javax.swing.JTextField PrecioTXT;
    private javax.swing.JLabel RegistrarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
