/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfacesApp;

/**
 *
 * @author MADE
 */
public class TablonInventario extends javax.swing.JPanel {

    /**
     * Creates new form TabloMateriales
     */
    public TablonInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorInventario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AgregarProducto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EliminarProducto = new javax.swing.JLabel();
        RegistarProducto = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 700));

        ContenedorInventario.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorInventario.setPreferredSize(new java.awt.Dimension(800, 700));
        ContenedorInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVENTARIO ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorInventario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 809, 80));

        AgregarProducto.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        AgregarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarProducto.setText("AGREGAR PRODUCTOS");
        AgregarProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarProductoMouseClicked(evt);
            }
        });
        ContenedorInventario.add(AgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 93, 180, 73));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(804, 440));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        ContenedorInventario.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 226, 809, 473));

        EliminarProducto.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        EliminarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarProducto.setText("ELIMINAR PRODUCTOS");
        EliminarProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarProductoMouseClicked(evt);
            }
        });
        EliminarProducto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                EliminarProductoPropertyChange(evt);
            }
        });
        ContenedorInventario.add(EliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 93, 180, 73));

        RegistarProducto.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        RegistarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistarProducto.setText("REGISTRAR PRODUCTOS");
        RegistarProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegistarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistarProductoMouseClicked(evt);
            }
        });
        ContenedorInventario.add(RegistarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 93, 180, 73));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ContenedorInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ContenedorInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarProductoMouseClicked
        NuevoInventario p = new  NuevoInventario();
        p.setSize(800, 700);
        ContenedorInventario.removeAll();
        ContenedorInventario.add(p);
        ContenedorInventario.revalidate();
        ContenedorInventario.repaint();
        ContenedorInventario.setSize(800, 700);
        ContenedorInventario.setLocation(200, 0);
       
    }//GEN-LAST:event_AgregarProductoMouseClicked

    private void EliminarProductoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_EliminarProductoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarProductoPropertyChange

    private void EliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarProductoMouseClicked
        EliminarInventario p = new  EliminarInventario();
        p.setSize(800, 700);
        ContenedorInventario.removeAll();
        ContenedorInventario.add(p);
        ContenedorInventario.revalidate();
        ContenedorInventario.repaint();
        ContenedorInventario.setSize(800, 700);
        ContenedorInventario.setLocation(200, 0);
    }//GEN-LAST:event_EliminarProductoMouseClicked

    private void RegistarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistarProductoMouseClicked
        RegistrarProducto p = new  RegistrarProducto();
        p.setSize(800, 700);
        ContenedorInventario.removeAll();
        ContenedorInventario.add(p);
        ContenedorInventario.revalidate();
        ContenedorInventario.repaint();
        ContenedorInventario.setSize(800, 700);
        ContenedorInventario.setLocation(200, 0);
    }//GEN-LAST:event_RegistarProductoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarProducto;
    private javax.swing.JPanel ContenedorInventario;
    private javax.swing.JLabel EliminarProducto;
    private javax.swing.JLabel RegistarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
